import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import Head from "next/head"
import YouTubePlayer from "react-youtube";

export default function Movie(props) {
  console.log(props)
  const movie = props

  const videoUrl = movie.trailers[0].url.slice(-11)

  const opts = {
    playerVars: {
      autoplay: 1,
      controls: 0,
    },
  };

  return (
    <>
      <Head>
        <title>KINOKASSA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />

        <h1>{movie.name}</h1>
        <h1>{movie.name}</h1>
        <h1>{movie.name}</h1>
        <h1>{movie.name}</h1>
        <YouTubePlayer opts={opts} videoId={videoUrl} />
        <Footer />
      </main>
    </>
  )
}

export const getServerSideProps = async (context) => {
  const { data } = context.query

  return { props: JSON.parse(data) }
}