import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import Head from "next/head"

export default function Movie() {


  return (
    <>
      <Head>
        <title>KINOKASSA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />

        <Footer />
      </main>
    </>
  )
}