import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import Head from "next/head"

export default function Premieres() {


    return (
        <>
            <Head>
                <title>KINOKASSA | Премьеры</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                premieres
                <Footer />
            </main>
        </>
    )
}